name: CI Build
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the Maven verify phase
        run: mvn clean verify -DappId=${{ secrets.APP_ID }} -Dcluster=${{ secrets.CLUSTER }} -DappKey=${{ secrets.APP_SECRET }} -Dauthority=${{ secrets.TENANT_ID }} -Ddatabase=${{ secrets.DATABASE }} -Dingest=${{ secrets.INGEST }}
        env:
          appId: ${{ secrets.APP_ID }}
          authority: ${{ secrets.TENANT_ID }}
          appKey: ${{ secrets.APP_SECRET }}
          database: ${{ secrets.DATABASE }}
          cluster: ${{ secrets.CLUSTER }}
          ingest: ${{ secrets.INGEST }}

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

